<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math"
    xmlns:map="http://www.w3.org/2005/xpath-functions/map"
    exclude-result-prefixes="xs math"
    version="3.0">
    
    <xsl:variable name="extent-map" as="map(xs:string, xs:string+)" select="map{
        '1 inch videotape': ('1 inch videotape', '1 inch videotapes'),
        (: Note:  we don't use videotapes as well right now, but just demoing here that we are treating
        both singular and plural extent types in ASpace the same.... i.e., in all cases we are recording both
        output options in this file, for a quick lookup :)
        '1 inch videotapes': ('1 inch videotape', '1 inch videotapes'),
        '1/2 inch videotape': ('1/2 inch videotape', '1/2 inch videotapes'),
        '2 inch videotape': ('2 inch videotape', '2 inch videotapes'),
        'acetate negatives': ('Acetate negative', 'Acetate negatives'),
        'albumen prints': ('Albumen print', 'Albumen prints'),
        'albums': ('Album', 'Albums'),
        'aluminum disc': ('Aluminum disc', 'Aluminum discs'),
        'ambrotypes (photographs)': ('Ambrotype (photograph)', 'Ambrotypes (photographs)'),
        'audio cartridge': ('Audio cartridge', 'Audio cartridges'),
        'audio cartridge (1/4 inch)': ('Audio cartridge (1/4 inch)', 'Audio cartridges (1/4 inch)'),
        'audio cartridge (8-track)': ('Audio cartridge (8-track)', 'Audio cartridges (8-track)'),
        'audio cartridge (fidelipac)': ('Audio cartridge (Fidelipac)', 'Audio cartridges (Fidelipac)'),
        'audio cassette': ('Audio cassette', 'Audio cassettes'),
        'audio cassette (dat)': ('Audio cassette (DAT)', 'Audio cassettes (DAT)'),
        'audio cassette (microcassette)': ('Audio cassette (Microcassette)', 'Audio cassettes (Microcassette)'),
        'audio cd': ('Audio CD', 'Audio CDs'),
        'autochromes (photographs)': ('Autochrome (photograph)', 'Autochromes (photographs)'),
        'awards': ('Award', 'Awards'),
        'binders': ('Binder', 'Binders'),
        'blueprints': ('Blueprint', 'Blueprints'),
        'booklets': ('Booklet', 'Booklets'),
        'books': ('Book', 'Books'),
        'boxes': ('Box', 'Boxes'),
        'brochures': ('Brochure', 'Brochures'),
        'cabinet photographs': ('Cabinet photograph', 'Cabinet photographs'),
        'cans (containers)': ('Can (container)', 'Cans (containers)'),
        'card photographs (photographs)': ('Card photograph (photograph)', 'Card photographs (photographs)'),
        'cartes-de-viste (card photographs)': ('Carte-de-viste (card photograph)', 'Cartes-de-viste (card photographs)'),
        'cartons (containers)': ('Carton (container)', 'Cartons (containers)'),
        'cased photographs': ('Cased photograph', 'Cased photographs'),
        'cassette tapes': ('Cassette tape', 'Cassette tapes'),
        'cassettes': ('Cassette', 'Cassettes'),
        'cd-rs': ('CD-R', 'CD-Rs'),
        'chromolithographs': ('Chromolithograph', 'Chromolithographs'),
        'clippings (books, newspapers, etc.)': ('Clipping (Book, newspaper, etc.)', 'Clippings (Books, newspapers, etc.)'),
        'color copy print': ('Color copy print', 'Color copy prints'),
        'color lithographs': ('Color lithograph', 'Color lithographs'),
        'color negatives': ('Color negative', 'Color negatives'),
        'color postcards': ('Color postcard', 'Color postcards'),
        'color prints': ('Color print', 'Color prints'),
        'color slides': ('Color slide', 'Color slides'),
        'color transparencies': ('Color transparency', 'Color transparencies'),
        'colored positive': ('Colored positive', 'Colored positives'),
        (: note the use of the XML character entity in the next string match :)
        'computer disc 3.5&quot;': ('Computer disc 3.5&quot;', 'Computer discs 3.5&quot;'),
        'computer storage devices': ('Computer storage device', 'Computer storage devices'),
        'contact prints': ('Contact print', 'Contact prints'),
        'contact sheets': ('Contact sheet', 'Contact sheets'),
        'containers': ('Container', 'Containers'),
        'copies': ('Copy', 'Copies'),
        'copies (derivative objects)': ('Copy (derivative object)', 'Copies (derivative objects)'),
        'copy color slides': ('Copy color slide', 'Copy color slides'),
        'copy lantern slides': ('Copy lantern slide', 'Copy lantern slides'),
        'copy negatives': ('Copy negative', 'Copy negatives'),
        'copy prints': ('Copy print', 'Copy prints'),
        'copy slides': ('Copy slide', 'Copy slides'),
        'copy stereograph': ('Copy stereograph', 'Copy stereographs'),
        'coupler prints (chromogenic)': ('Coupler print (chromogenic)', 'Coupler prints (chromogenic)'),
        'cubic feet': ('Cubic foot', 'Cubic feet'),
        'cultural artifacts': ('Cultural artifact', 'Cultural artifacts'),
        'cyanotypes (photographic prints)': ('Cyanotype (photographic print)', 'Cyanotypes (photographic prints)'),
        'daguerreotypes (photographs)': ('Daguerreotype (photograph)', 'Daguerreotypes (photographs)'),
        'data cartridges': ('Data cartridge', 'Data cartridges'),
        'diaries': ('Diary', 'Diaries'),
        'digital files': ('Digital file', 'Digital files'),
        'digital images': ('Digital image', 'Digital images'),
        'digital prints': ('Digital print', 'Digital prints'),
        'digital scans': ('Digital scan', 'Digital scans'),
        'direct positives': ('Direct positive', 'Direct positives'),
        'discs': ('Disc', 'Discs'),
        'documents': ('Document', 'Documents'),
        'drawings (visual works)': ('Drawing (visual work)', 'Drawings (visual works)'),
        'electronic discs (cd)': ('Electronic disc (CD)', 'Electronic discs (CD)'),
        'engravings': ('Engraving', 'Engravings'),
        'enlarged prints': ('Enlarged print', 'Enlarged prints'),
        'envelopes': ('Envelope', 'Envelopes'),
        'exhibition catalogs': ('Exhibition catalog', 'Exhibition catalogs'),
        'file drawers': ('File drawer', 'File drawers'),
        'files': ('File', 'Files'),
        'files (document groupings)': ('File (document grouping)', 'Files (document groupings)'),
        'film cassettes': ('Film cassette', 'Film cassettes'),
        'film items': ('Film item', 'Film items'),
        'film loops': ('Film loop', 'Film loops'),
        'film negative': ('Film negative', 'Film negatives'),
        'film positives': ('Film positive', 'Film positives'),
        'film transparency': ('Film transparency', 'Film transparencies'),
        'floppy discs': ('Floppy disc', 'Floppy discs'),
        'folders': ('Folder', 'Folders'),
        'frames': ('Frame', 'Frames'),
        'full coat magnetic audio (16mm)': ('Full coat magnetic audio film (16mm)', 'Full coat magnetic audio films (16mm)'),
        'full coat magnetic audio (35mm)': ('Full coat magnetic audio film (35mm)', 'Full coat magnetic audio films (35mm)'),
        'gelatin silver prints': ('Gelatin silver print', 'Gelatin silver prints'),
        'gelatin silver transparencies': ('Gelatin silver transparency', 'Gelatin silver transparencies'),
        'gigabytes': ('Gigabyte', 'Gigabytes'),
        'glass negatives': ('Glass negative', 'Glass negatives'),
        'glass plate negatives': ('Glass plate negative', 'Glass plate negatives'),
        'glass plate stereographic negatives': ('Glass plate stereographic negative', 'Glass plate stereographic negatives'),
        'glass positives': ('Glass positive', 'Glass positives'),
        'glass slides': ('Glass slide', 'Glass slides'),
        'glass transparencies': ('Glass transparency', 'Glass transparencies'),
        'graphite drawings': ('Graphite drawing', 'Graphite drawings'),
        'grooved audio disc': ('Grooved audio disc', 'Grooved audio discs'),
        'grooved dictabelt': ('Grooved Dictabelt', 'Grooved Dictabelts'),
        'hard drives': ('Hard drive', 'Hard drives'),
        'hours audio tape': ('Hours audio tape', 'Hours audio tape'),
        'issues (object groupings)': ('Issue (object grouping)', 'Issues (object groupings)'),
        'items': ('Item', 'Items'),
        'lacquer disc': ('Lacquer disc', 'Lacquer discs'),
        'lantern slides': ('Lantern slide', 'Lantern slides'),
        'leaves': ('Leaf  ', 'Leaves'),
        'leaves (gathered matter)': ('Leaf (gathered matter)', 'Leaves (gathered matter)'),
        'leaves (gathered matter components)': ('Leaf (gathered matter)', 'Leaves (gathered matter)'),
        'ledgers': ('Ledger', 'Ledgers'),
        'legal documents': ('Legal document', 'Legal documents'),
        'letters': ('Letter', 'Letters'),
        'linear feet': ('Linear Foot', 'Linear Feet'),
        'lithographs': ('Lithograph', 'Lithographs'),
        'magazines (periodicals)': ('Magazine (periodical)', 'Magazines (periodicals)'),
        'manuscripts (document genre)': ('Manuscript (document genre)', 'Manuscripts (document genre)'),
        'map drawers': ('Map drawer', 'Map drawers'),
        'maps': ('Map', 'Maps'),
        'megabytes': ('Megabyte', 'Megabytes'),
        'memory cards': ('Memory card', 'Memory cards'),
        'microfiches': ('Microfiche', 'Microfiches'),
        'microfilm': ('Microfilm', 'Microfilms'),
        'microfilm reels': ('Microfilm reel', 'Microfilm reels'),
        'minidisc': ('MiniDisc', 'MiniDiscs'),
        'motion picture film': ('Motion picture film', 'Motion picture films'),
        'motion picture film (16mm)': ('Motion picture film (16mm)', 'Motion picture films (16mm)'),
        'motion picture film (35mm)': ('Motion picture film (35mm)', 'Motion picture films (35mm)'),
        'motion picture film (60mm)': ('Motion picture film (60mm)', 'Motion picture films (60mm)'),
        'motion picture film (66mm)': ('Motion picture film (66mm)', 'Motion picture films (66mm)'),
        'motion picture film (70mm)': ('Motion picture film (70mm)', 'Motion picture films (70mm)'),
        'motion picture film (8mm)': ('Motion picture film (8mm)', 'Motion picture films (8mm)'),
        'motion picture film (cartridge)': ('Motion picture film (cartridge)', 'Motion picture films (cartridge)'),
        'motion picture film (super 16mm)': ('Motion picture film (Super 16mm)', 'Motion picture films (Super 16mm)'),
        'motion picture film (super 8mm)': ('Motion picture film (Super 8mm)', 'Motion picture films (Super 8mm)'),
        'negative prints': ('Negative print', 'Negative prints'),
        'negative rolls': ('Negative roll', 'Negative rolls'),
        'negatives (photographic)': ('Negative (photographic)', 'Negatives (photographic)'),
        'nitrate negatives': ('Nitrate negative', 'Nitrate negatives'),
        'notebooks': ('Notebook', 'Notebooks'),
        'open reel audiotape': ('Open reel audiotape', 'Open reel audiotapes'),
        'open reel audiotape (1 inch)': ('Open reel audiotape (1 inch)', 'Open reel audiotapes (1 inch)'),
        'open reel audiotape (1/2 inch)': ('Open reel audiotape (1/2 inch)', 'Open reel audiotapes (1/2 inch)'),
        'open reel audiotape (1/4 inch)': ('Open reel audiotape (1/4 inch)', 'Open reel audiotapes (1/4 inch)'),
        'open reel audiotape (2 inch)': ('Open reel audiotape (2 inch)', 'Open reel audiotapes (2 inch)'),
        'open reel videotape': ('Open reel videotape', 'Open reel videotapes'),
        'optical video disc': ('Optical video disc', 'Optical video discs'),
        'optical video disc (blu-ray)': ('Optical video disc (Blu-ray)', 'Optical video discs (Blu-ray)'),
        'optical video disc (dvd)': ('Optical video disc (DVD)', 'Optical video discs (DVD)'),
        'optical video disc (laserdisc)': ('Optical video disc (LaserDisc)', 'Optical video discs (LaserDisc)'),
        'oversize folders': ('Oversize folder', 'Oversize folders'),
        'pages': ('Page', 'Pages'),
        'painted photographs': ('Painted photograph', 'Painted photographs'),
        'paintings (visual works)': ('Painting (visual work)', 'Paintings (visual works)'),
        'pamphlets': ('Pamphlet', 'Pamphlets'),
        'panoramic print': ('Panoramic print', 'Panoramic prints'),
        'perspective drawing': ('Perspective drawing', 'Perspective drawings'),
        'phonograph records': ('Phonograph record', 'Phonograph records'),
        'photocopies': ('Photocopy', 'Photocopies'),
        'photograph (digital)': ('Photograph (digital)', 'Photographs (digital)'),
        'photograph albums': ('Photograph album', 'Photograph albums'),
        'photographic postcards': ('Photographic postcard', 'Photographic postcards'),
        'photographic prints': ('Photographic print', 'Photographic prints'),
        'photographic slides': ('Photographic slide', 'Photographic slides'),
        'photographic transparencies': ('Photographic transpareny', 'Photographic transparencies'),
        'photographs': ('Photograph', 'Photographs'),
        'photomechanical prints': ('Photomechanical print', 'Photomechanical prints'),
        'pictographs': ('Pictograph', 'Pictographs'),
        'plates': ('Plate', 'Plates'),
        'platinum prints': ('Platinum print', 'Platinum prints'),
        'polaroid prints': ('Polaroid print', 'Polaroid prints'),
        'polyester negatives': ('Polyester negative', 'Polyester negatives'),
        'portfolios': ('Portfolio', 'Portfolios'),
        'positive rolls': ('Positive roll', 'Positive rolls'),
        'positives (photographs)': ('Positive (photograph)', 'Positives (photographs)'),
        'postage stamps': ('Postage stamp', 'Postage stamps'),
        'postcards': ('Postcard', 'Postcards'),
        'posters': ('Poster', 'Posters'),
        'printed pages': ('Printed page', 'Printed pages'),
        'printing plates': ('Printing plate', 'Printing plates'),
        'prints': ('Print', 'Prints'),
        'prints (halftone)': ('Print (halftone)', 'Prints (halftone)'),
        'prints (visual works)': ('Print (visual work)', 'Prints (visual works)'),
        'prints and postcards': ('Print and/or postcard', 'Prints and postcards'),
        'reels': ('Reel', 'Reels'),
        'roll': ('Roll', 'Rolls  '),
        'rolls of negatives': ('Roll of negatives', 'Rolls of negatives'),
        'safety film': ('Safety film', 'Safety films'),
        'safety film negative': ('Safety film negative', 'Safety film negatives'),
        'scholarly periodicals': ('Scholarly periodical', 'Scholarly periodicals'),
        'scrapbooks': ('Scrapbook', 'Scrapbooks'),
        'sections': ('Section', 'Sections'),
        'sheets': ('Sheet', 'Sheets'),
        'shoeboxes': ('Shoebox', 'Shoeboxes'),
        'sketched map': ('Sketched map', 'Sketched maps'),
        'sketches': ('Sketch', 'Sketches'),
        'slide boxes': ('Slide box', 'Slide boxes'),
        'slide viewers': ('Slide viewer', 'Slide viewers'),
        'slides (photographs)': ('Slide (photograph)', 'Slides (photographs)'),
        'sound cylinders': ('Sound cylinder', 'Sound cylinders'),
        'sound disk cd-r': ('Sound disk CD-R', 'Sound disk CD-Rs'),
        'sound recordings': ('Sound recording', 'Sound recordings'),
        'sound tapes': ('Sound tape', 'Sound tapes'),
        'sound track film reels': ('Sound track film reel', 'Sound track film reels'),
        'sound wire reels': ('Sound wire reel', 'Sound wire reels'),
        'stamps': ('Stamp', 'Stamps'),
        'stereo negatives': ('Stereo negative', 'Stereo negatives'),
        'stereographs': ('Stereograph', 'Stereographs'),
        'terabytes': ('Terabyte', 'Terabytes'),
        'tintypes': ('Tintype', 'Tintypes'),
        'trade catalogs': ('Trade catalog', 'Trade catalogs'),
        'transparencies': ('Transparency', 'Transparencies'),
        'type-c prints (color coupler)': ('Type-C print (color coupler)', 'Type-C prints (color coupler)'),
        'usb flash drive': ('USB flash drive', 'USB flash drives'),
        'video cartridge': ('Video cartridge', 'Video cartridges'),
        'video recordings': ('Video recording', 'Video recordings'),
        'videocassette': ('Videocassette', 'Videocassettes'),
        'videocassette (beta)': ('Videocassette (Beta)', 'Videocassettes (Beta)'),
        'videocassette (betacam)': ('Videocassette (Betacam)', 'Videocassettes (Betacam)'),
        'videocassette (betacamsp)': ('Videocassette (BetacamSP)', 'Videocassettes (BetacamSP)'),
        'videocassette (betamax)': ('Videocassette (Betamax)', 'Videocassettes (Betamax)'),
        'videocassette (d1)': ('Videocassette (D1)', 'Videocassettes (D1)'),
        'videocassette (d2)': ('Videocassette (D2)', 'Videocassettes (D2)'),
        'videocassette (d3)': ('Videocassette (D3)', 'Videocassettes (D3)'),
        'videocassette (digital 8)': ('Videocassette (Digital 8)', 'Videocassettes (Digital 8)'),
        'videocassette (digital betacam)': ('Videocassette (Digital Betacam)', 'Videocassettes (Digital Betacam)'),
        'videocassette (dvcam)': ('Videocassette (DVCam)', 'Videocassettes (DVCam)'),
        'videocassette (dvcpro)': ('Videocassette (DVCPro)', 'Videocassettes (DVCPro)'),
        'videocassette (hdcam-sr)': ('Videocassette (HDCAM-SR)', 'Videocassettes (HDCAM-SR)'),
        'videocassette (hdcam)': ('Videocassette (HDCam)', 'Videocassettes (HDCam)'),
        'videocassette (hi8)': ('Videocassette (Hi8)', 'Videocassettes (Hi8)'),
        'videocassette (minidv)': ('Videocassette (MiniDV)', 'Videocassettes (MiniDV)'),
        'videocassette (s-vhs)': ('Videocassette (S-VHS)', 'Videocassettes (S-VHS)'),
        'videocassette (u-matic s)': ('Videocassette (U-matic S)', 'Videocassettes (U-matic S)'),
        'videocassette (u-matic sp)': ('Videocassette (U-matic SP)', 'Videocassettes (U-matic SP)'),
        'videocassette (u-matic)': ('Videocassette (U-matic)', 'Videocassettes (U-matic)'),
        'videocassette (vhs-c)': ('Videocassette (VHS-C)', 'Videocassettes (VHS-C)'),
        'videocassette (vhs)': ('Videocassette (VHS)', 'Videocassettes (VHS)'),
        'videocassette (video 8)': ('Videocassette (Video 8)', 'Videocassettes (Video 8)'),
        'videocassette (xdcam)': ('Videocassette (XDCAM)', 'Videocassettes (XDCAM)'),
        'vinyl record': ('Vinyl record', 'Vinyl records'),
        'visual works (works)': ('Visual work (work)', 'Visual works (works)'),
        'volumes': ('Volume', 'Volumes'),
        'watercolor': ('Watercolor', 'Watercolors'),
        'wire recording': ('Wire recording', 'Wire recordings')
        }"
    />
       
</xsl:stylesheet>